### PR TITLE
Fix send empty message and trim spaces at beginning and end of message

### LINKED ISSUE #255: User is able to send blank messages in chat
**Issue:** Like title says, user is able to send blank messages in chat 

**How to replicate:**
1. Start chat 
2. Press space key a bunch 
3. Send blank message 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/200657084-e12f74c3-687c-4988-8c21-b631fb35720c.mov

### PR DESCRIPTION
**Pull request by lgmarchi**
### 2. Trim spaces at beginning and end of message 

image

https://user-images.githubusercontent.com/63157656/201202600-6aae9999-4373-4cb2-b7e9-7e808190072b.mov

### Which issue(s) this PR fixes 🔨
- Resolve #255

### CODE REVIEW

File: src/components/ui_kit/textarea/mod.rs [hunk 1]
```diff
@@ -51,7 +51,9 @@ pub fn TextArea<'a>(
                 },
                 onkeyup: |e| {
                     if e.data.key_code.eq(&KeyCode::Enter) && !e.data.shift_key {
-                        on_submit.call(text.to_string());
+                        if !text.trim().is_empty() {
```
Comment (dariusc93) [inline src/components/ui_kit/textarea/mod.rs:54]: Might be better do so the following 
```suggestion
let text = text.trim();
if !text.is_empty() {
   on_submit.call(text.to_string());
}
```

(not required to accept just a suggestion)

**Review by dariusc93 — APPROVED** [review]
This was fixed in warp too (somehow slipped passed being committed) but its good to check in the UI too.
